[project]
name = "json-to-garmin"
version = "0.1.0"
description = "Generic JSON-defined workouts → Garmin Connect"
authors = [{ name = "Thomas Fuchs", email = "thomas@fuchs.one"}]
requires-python = ">=3.13, <3.14"
dependencies = [
    "pydantic>=2.10,<3.0",
    "garminconnect>=0.3.2,<1.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0,<9.0",
]

[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{ include = "json_to_garmin", from = "src" }]

[tool.pytest.ini_options]
testpaths = ["tests"]
